---
title: "Final Project: Covid 19 Around the World"
description: |
  "By using owid Covid 19 data and statistics, I examined trends."
site: distill::distill_website
---

```{r setup, include=FALSE, layout = "l-body-outset"}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggthemes)
library(knitr)
library(rmarkdown)
library(gt)
```

```{r}
raw_data <- read_csv(file="owid-covid-data.csv")
```

```{r Covid-plot}

clean_data <-raw_data %>% 
  select(continent, total_cases) %>% 
  drop_na() %>% 
  group_by(continent) %>% 
  summarize(continent_cases=sum(total_cases)) 
clean_data %>% 
  ggplot(mapping=aes(x=continent,y=continent_cases,fill=continent))+
  geom_col()+
  scale_y_continuous(labels = scales::number_format())+
  labs(title="Covid Cases per Continent",subtitle="Developed and Populated Continents with Higher Cases", x="Continent",y="Continent Cases",fill="Continents")

```
Initial Data shows a shockingly low amount of Covid Cases in Africa compared to other continents. 

```{r}
clean_data1 <- raw_data %>% 
  select(continent, total_deaths) %>% 
  drop_na() %>% 
  group_by(continent) %>% 
  summarize(continent_deaths=sum(total_deaths)) 
clean_data1 %>% 
  ggplot(mapping=aes(x=continent,y=continent_deaths,fill=continent))+
  geom_col()+
  scale_y_continuous(labels = scales::number_format())+
  labs(title="Covid Deaths per Continent",subtitle="Developed and Populated Continents with Higher Deaths", x="Continent",y="Continent Deaths",fill="Continents")
```
